### ISSUE TITLE
[Vintage] Review IamActuallyLvL1's changes and merge them back

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGOFormatData#111]
I noticed that @IamActuallyLvL1 has applied some changes to his fork, we should review which ones are interesting and merge them back.

I made a quick attempt to merge them direcly but it's conflicting with @Jiliac's March update (983e532b71a26c8b3f6fdf5bd6f3329394ae7792), so some manual resolution or cherry-picking will be required.

**Comment by Jiliac** [comment]
ok looking at it

**Comment by Jiliac** [comment]
merged ✅

**Comment by Badaro** [comment]
Wow, fast, thanks @Jiliac! :)

I had this written down more of as a reminder, didn't expect it done this fast.

**Comment by Jiliac** [comment]
@IamActuallyLvL1 It's true. Most notably over conflict management since you do a hand pass and a "main/sub-archetype" differenciation.

However, you are the one with the most knowledge. I'm just a vintage tourist 😅  There are still some difference but I'd rather keep as close as possible to your definitions (and to make future merge easier to do).
